// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtkjkhbnsdytmvohyoka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10a2praGJuc2R5dG12b2h5b2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTQwOTQsImV4cCI6MjA3MDY5MDA5NH0.jFEubz0fEwnNyWIcWGHxXUJIBrisZVFh3-OblI9W9Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});